FROM golang:1.22-alpine

WORKDIR /app

RUN apk add --no-cache git ca-certificates protobuf-dev

COPY go.mod go.sum ./
RUN go mod download

COPY . .

EXPOSE 50051

CMD ["go", "run", "cmd/server/main.go"]
